PATが古い場合はCIの一番最初で落とす

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -15,6 +15,18 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Check if GitHub PAT is valid
+        run: |
+          response=$(curl -o /dev/null -s -w "%{http_code}\n" \
+                    -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
+                    -H "Accept: application/vnd.github.v3+json" \
+                    https://api.github.com/user)
+
+          if [ "$response" -ne 200 ]; then
+            echo "GitHub PAT is invalid or expired"
+            exit 1
+          fi
+
       - uses: actions/checkout@v3
       - name: Setup gcloud environment
         uses: google-github-actions/setup-gcloud@v0
